//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "fetch_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub run_id: Uuid,
    pub url_id: Uuid,
    pub fetched_at: DateTimeWithTimeZone,
    pub http_status: Option<i32>,
    pub response_time_ms: i64,
    pub bytes: i64,
    #[sea_orm(column_type = "Text")]
    pub outcome: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub etag: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_modified: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub raw_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub body_hash: Option<String>,
    pub extractor_version: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub declared_canonical_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_detail: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::crawl_runs::Entity",
        from = "Column::RunId",
        to = "super::crawl_runs::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CrawlRuns,
    #[sea_orm(
        belongs_to = "super::urls::Entity",
        from = "Column::UrlId",
        to = "super::urls::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Urls,
}

impl ActiveModelBehavior for ActiveModel {}
