//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod areas;
pub mod content_versions;
pub mod crawl_runs;
pub mod fetch_history;
pub mod host_moves;
pub mod program_urls;
pub mod programs;
pub mod resources;
pub mod url_resources;
pub mod urls;
