//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::areas::Entity as Areas;
pub use super::program_urls::Entity as ProgramUrls;
pub use super::programs::Entity as Programs;
pub use super::urls::Entity as Urls;
