//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "program_urls")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub program_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub url_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub role: String,
    pub rank: i32,
    #[sea_orm(column_type = "Text")]
    pub source: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::programs::Entity",
        from = "Column::ProgramId",
        to = "super::programs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Programs,
    #[sea_orm(
        belongs_to = "super::urls::Entity",
        from = "Column::UrlId",
        to = "super::urls::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Urls,
}

impl Related<super::programs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Programs.def()
    }
}

impl Related<super::urls::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Urls.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
