//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "programs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub psid: String,
    #[sea_orm(column_type = "Text")]
    pub um: String,
    #[sea_orm(column_type = "Text")]
    pub area_code: String,
    #[sea_orm(column_type = "Text")]
    pub canonical_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub short_name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub source_url: String,
    pub category_codes: Vec<String>,
    pub target_codes: Vec<String>,
    pub content_codes: Vec<String>,
    pub age_min_months: Option<i32>,
    pub age_max_months: Option<i32>,
    #[sea_orm(column_type = "JsonBinary")]
    pub registry: Json,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub checked_at: Option<DateTimeWithTimeZone>,
    pub imported_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::areas::Entity",
        from = "Column::AreaCode",
        to = "super::areas::Column::Code",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Areas,
}

impl Related<super::areas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Areas.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
