//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "resources")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub canonical_url: String,
    #[sea_orm(column_type = "Text")]
    pub final_url: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub declared_canonical_url: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub canonical_source: String,
    #[sea_orm(column_type = "Text")]
    pub state: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub etag: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_modified: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub raw_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub page_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub title_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub body_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub links_hash: Option<String>,
    pub page_updated_on: Option<Date>,
    pub extractor_version: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub extractor_rule: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub robots_meta: Option<String>,
    pub last_crawled_at: Option<DateTimeWithTimeZone>,
    pub last_changed_at: Option<DateTimeWithTimeZone>,
    pub next_crawl_at: Option<DateTimeWithTimeZone>,
    pub consecutive_not_found: i32,
    pub moved_to_resource_id: Option<Uuid>,
    pub change_count: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::MovedToResourceId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::url_resources::Entity")]
    UrlResources,
}

impl Related<super::url_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UrlResources.def()
    }
}

impl Related<super::urls::Entity> for Entity {
    fn to() -> RelationDef {
        super::url_resources::Relation::Urls.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::url_resources::Relation::Resources.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
