//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "url_resources")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub url_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub resource_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub relation: String,
    pub observed_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::resources::Entity",
        from = "Column::ResourceId",
        to = "super::resources::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Resources,
    #[sea_orm(
        belongs_to = "super::urls::Entity",
        from = "Column::UrlId",
        to = "super::urls::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Urls,
}

impl Related<super::resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Resources.def()
    }
}

impl Related<super::urls::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Urls.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
