//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "urls")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub raw_url: String,
    #[sea_orm(column_type = "Text")]
    pub normalized_url: String,
    #[sea_orm(column_type = "Text", unique)]
    pub dedup_key: String,
    #[sea_orm(column_type = "Text")]
    pub host_key: String,
    #[sea_orm(column_type = "Text")]
    pub role: String,
    pub depth: i32,
    pub priority: i32,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub next_crawl_at: DateTimeWithTimeZone,
    pub last_crawled_at: Option<DateTimeWithTimeZone>,
    pub attempt_count: i32,
    pub retry_count: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub worker_id: Option<String>,
    pub lease_until: Option<DateTimeWithTimeZone>,
    pub claim_token: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error_type: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::program_urls::Entity")]
    ProgramUrls,
    #[sea_orm(has_many = "super::url_resources::Entity")]
    UrlResources,
}

impl Related<super::program_urls::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProgramUrls.def()
    }
}

impl Related<super::url_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UrlResources.def()
    }
}

impl Related<super::resources::Entity> for Entity {
    fn to() -> RelationDef {
        super::url_resources::Relation::Resources.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::url_resources::Relation::Urls.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
